import Head from 'next/head';
import styles from '@/styles/AccountCreated.module.css';
import Image from 'next/image';

export default function AccountCreated() {

    return (
      <>
        <Head>
          <title>Account Created</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
          <div className={styles.iphoneFrame}>
            <main className={`${styles.main}`}>
              <div className={styles.container}>
                <div className={styles.header}>
                    <h1>Awesome!</h1>
                    <h3>Here is your account!</h3>
                </div>
                <div className={styles.cardBackground}> 
                    <div className={styles.progressBar}>
                        <Image src="/images/OnboardingImages/progressbar3.svg" alt="accountCreated" width={352} height={31} />
                    </div>
                    <div className={styles.innerContainer}>
                        <h3>Jalen Smith</h3>
                        <div className={styles.placeholderImage}></div>
                        <Image className={styles.addPhotoIcon} src="../images/OnboardingImages/addPhotoIcon.svg" alt="addPhotoIcon" width={39} height={39} />
                        <p className={styles.text}><span className={styles.span}>Name:</span> Jalen Smith</p>
                        <p className={styles.text}><span className={styles.span}>Userame:</span> jay_smitty</p>
                        <p className={styles.text}><span className={styles.span}>E-mail:</span> jalensmith@gmail.com</p>
                        <p className={styles.text}><span className={styles.span}>Phone:</span> <span className={styles.span2}>+1</span> (604) 563-5242</p>
                        <button className={styles.button}>Edit Info</button>
                        <button className={styles.button2}>Looks Good!</button>
                </div>
                </div>
              </div>
            </main>
          </div>
        </>
    )
}
