import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import NavBar from '@/components/NavBar';
import TabBar from '@/components/TabBar';
import HomeRepairsCardSection from '@/components/HomeRepairsCardSection';

export default function HomeRepairs() {

    const headerTitle = 'Home Repairs';
    const pageLayout = 'layout1';
    const backButton = false;
    const searchBar = true;
    const settings = true;
  
    return (
      <>
        <Head>
          <title>Home Repairs</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.iphoneFrame}>
          <NavBar layout={pageLayout} title={headerTitle} backButton={backButton} />
          <main className={`${styles.main}`}>
            <HomeRepairsCardSection/>
          </main>
          <TabBar/>
        </div>
      </>
    )
  } 
  