import Head from 'next/head';
import styles from '@/styles/JamesPlunk.module.css';
import NavBar from '@/components/NavBar';
import TabBar from '@/components/TabBar';
import Image from 'next/image';
import Link from 'next/link';
import ButtonBox from '@/components/ButtonBox';

export default function JamesPlunk() {

  const headerTitle = 'Services';
  const pageLayout = 'layout1';
  const backButton = true;
  const searchBar = true;
  const settings = false;

  return (
    <>
      <Head>
        <title>Home Repairs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.iphoneFrame}>
        <NavBar layout={pageLayout} title={headerTitle} backButton={backButton} searchBar={searchBar} settings={settings}/>
        <main className={`${styles.main}`}>
          <div className={styles.mainInnerContainer}>

            <div className={styles.mainImage}>
                <Image src="/images/jamesPlunkPageImages/jamesPlunk.svg" alt="James Plunk" width={398} height={330} />
            </div>

            <div className={styles.mainName}>
                <div className={styles.mainNameContainer}>
                    <p className={styles.nametitle}>James Plunk</p>
                    <div className={styles.spacingLine}></div>
                    <p>Plumber</p>
                </div>
            </div>

            <div className={styles.serviceDetails}>
                <p className={styles.serviceDetailsHeader}>Service Details</p>
                <p className={styles.serviceDetailsBody}>I am a plumber with 10 years experience, and I am certain I can fix any small issues you have around your house. Book an appointment now! I am a plumber with 10 years experience, and I am certain I can fix any small issues you have around your house. Book an appointment now!</p>
                    <div className={styles.spacingLine2}></div>
                <p className={styles.serviceDetailsBody}><span className={styles.span}>Hourly Pricing:</span> $20.00</p>
                <p className={styles.serviceDetailsBody}><span className={styles.span}>Availibility:</span> Mon - Thurs</p>
            </div>
            
            <div className={styles.bookButton}>
              <ButtonBox buttonText="Book Now" link="/BookService" />
              {/* <Link className={styles.link} href="/bookService">
                <p>Book Now</p>
              </Link> */}
            </div>

            <div className={styles.reviewsContainer}>
                <div className={styles.reviewsLeftCol}>
                    <p className={styles.reviewsHeader}>Most Recent Review</p>
                    <div className={styles.roseInfo}>
                        <Image src="/images/jamesPlunkPageImages/roseLPhoto.svg" alt="Rose L. Photo" width={64} height={64} />
                        <p>Rose L.</p>
                        <div className={styles.spacingLine3}></div>
                        <p>★★★★★</p>
                    </div>
                    <div className={styles.roseReview}>
                        <p>James was very helpful with changing my broken toilet. He was respectful and came on time and got the work done in a timely manner. Highly recommend!</p>
                    </div>
                </div>
                <div className={styles.reviewsRightCol}>
                    <p>Services Preformed</p>
                    <h1>78</h1>
                    <div className={styles.spacingLine4}></div>
                    <p>Rating</p>
                    <h1>4.7/5</h1>
                </div>
          </div>

          <div className={styles.bottomContainer}>
              <div className={styles.detailsHeader}>
                  <p>Details</p>
              </div>
                <div className={styles.detailsContainer}>
                    <p>Lives in <span className={styles.span}>Mount Pleasant</span> Neighborhood</p>
                    <p>Speaks <span className={styles.span}>English</span> and <span className={styles.span}>Italian</span></p>
                </div>
                <div className={styles.spacingLine5}></div>
                <div className={styles.reviewSummary}>
                    <p>James' Review Summary</p>
                </div>
                <div className={styles.reviewBubbles}>
                    <div className={styles.bubble1}><p>Friendliness (8)</p></div>
                    <div className={styles.bubble2}><p>Punctuality (4)</p></div>
                    <div className={styles.bubble3}><p>Clarity (6)</p></div>
                    <div className={styles.bubble4}><p>Communication (5)</p></div>
                    <div className={styles.bubble5}><p>Prompt Payment (3)</p></div>
                </div>
                <div className={styles.spacingLine6}></div>
                {/* <div className={styles.messageField}>
                    <input type="text" placeholder="Enter your message:" />
                </div>
                <div className={styles.messageButton}>
                    <p>Send Message</p>
                </div> */}
          </div>
            </div>
        </main>
        <TabBar/>
      </div>
    </>
  )
}
