import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import NavBar from '@/components/NavBar';
import TabBar from '@/components/TabBar';
import Link from 'next/link';
import style from '../styles/Landing.module.css';
import Image from 'next/image';
import { Providers } from 'next-auth/react'; 
import { signIn } from 'next-auth/react'; 
import Map from '@/components/Map';

export default function Landing() {
  const headerTitle = 'Welcome, {user}!';
  const pageLayout = 'layout1';
  const backButton = true;
  const searchBar = true;
  const settings = true;

  const handleFacebookSignIn = () => {
    signIn('facebook'); 
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.iphoneFrame}>
        <NavBar layout={pageLayout} title={headerTitle} backButton={backButton} />
        <main className={`${styles.main}`}>
          <div className={styles.mainInnerContainer}>
            <div className={style.logoContainer}>
              <h1>Neighbourly</h1>
            </div>
            
            <div className={style.boxContainer}>
              <h2>Login/Sign Up</h2>
            </div>
            
            <button>
              <Link href="/signUp">
                Sign Up
              </Link>
            </button>
            
            Already have an account?
            
            <button>
              <Link href="/signIn">
                Sign In
              </Link>
            </button>
            
            <p>or</p>
            <p>Continue with</p>
            
            <div>
              <Image 
                src='/images/signInIcons/facebook.svg'
                width={27}
                height={28}
                onClick={handleFacebookSignIn}
              />
              <Image 
                src='/images/signInIcons/apple.svg'
                width={27}
                height={28}
              />
              <Image 
                src='/images/signInIcons/google.svg'
                width={27}
                height={28}
              />
            </div>
          </div>
        </main>
        <TabBar/>
      </div>
    </>
  );
}
