import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import NavBar from '@/components/NavBar';
import TabBar from '@/components/TabBar';
import ApplicationForm from '@/components/ApplicationForm';

export default function MentorApplication() {

  const headerTitle = 'Mentee Application';
  const pageLayout = 'layout1';
  const backButton = true;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.iphoneFrame}>
        <NavBar layout={pageLayout} title={headerTitle} backButton={backButton} />
        <main className={`${styles.main}`}>
          <div className={styles.mainInnerContainer}>
            <ApplicationForm/>
          </div>
        </main>
        <TabBar/>
      </div>
    </>
  )
} 
