import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Onboarding.module.css';
import Head from 'next/head';
import { motion } from 'framer-motion';

export default function Onboarding1() {
  const [isExiting, setIsExiting] = useState(false);

  const handleClick = () => {
    setIsExiting(true);
    setTimeout(() => {
      window.location.href = '/Onboarding2';
    }, 1000); 
  };

  const backButton = true;
  const searchBar = true;
  const settings = true;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div className={styles.iphoneFrame}>
        <main className={`${styles.main}`}>
          <motion.div className={styles.container}>
            <motion.div 
              className={`${styles.topText}`}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
            >
              <h1>Welcome!</h1>
              <h3>Let's get started,</h3>
            </motion.div>
            <motion.div 
              className={`${styles.cardBackground}`}
              initial={{ opacity: 0, x: 0 }}
              animate={isExiting ? { x: -420 } : { opacity: 1 }}
              transition={{ duration: 1, ease: "easeIn" }}
              >
              <div className={styles.image}>
                <Image src="/images/OnboardingImages/onboarding1.svg" alt="Onboarding1" width={324} height={296} />
              </div>
              <motion.div 
                className={`${styles.bodyText}`}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5, delay: 0.5 }}
              >
                <p>Welcome to Neighbourly! A community <br></br> driven app that lets <br></br>everyone helps everyone!</p>
              </motion.div>
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5, delay: 1 }}
              >
                <button className={styles.button} onClick={handleClick}>Continue</button>
              </motion.div>
            </motion.div>
          </motion.div>
        </main>
      </motion.div>
    </>
  );
}