import Head from 'next/head';
import styles from '@/styles/Onboarding.module.css';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { motion } from 'framer-motion';


export default function Onboarding2() {
  const [isExiting, setIsExiting] = useState(false);

  const handleClick = () => {
    setIsExiting(true);
    setTimeout(() => {
      window.location.href = '/Onboarding3';
    }, 1000); 
  };

    const headerTitle = 'Welcome, {user}!';
    const pageLayout = 'layout1';
    const backButton = true;
    const searchBar = true;
    const settings = true;

    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <div className={styles.iphoneFrame}>
            <main className={`${styles.main}`}>
            <div className={styles.container}>
            <div className={`${styles.topText}`}>
                    <h1>Welcome!</h1>
                    <h3>Let's get started,</h3>
                </div>
                <motion.div 
                  className={`${styles.cardBackground}`}
                  initial={{ opacity: 0, x: 420 }}
                  animate={isExiting ? { opacity: 0, x: -420 } : { opacity: 1, x: 0 }}
                  transition={{ duration: 1, ease: "easeIn" }}
                  >                    
                    <div className={styles.image}>
                        <Image src="/images/quiz/gnome2.svg" alt="Onboarding1" width={495} height={312} />
                    </div>
                    
                    <motion.div 
                      className={`${styles.bodyText}`}
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ duration: 0.5, delay: 0.5 }}
                      >                       
                        <p>Within Neighbourly you can help others with tasks, or do the tasks to help others. Making some extra money and helping your community at the same time!</p>
                    </motion.div>
                    <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5, delay: 1 }}
              >                        <button className={styles.button01} onClick={handleClick}>Continue</button>
                    </motion.div>
                    </motion.div>
                   
                </div>
            </main>
          </div>
        </>
    )
}
