import Head from 'next/head';
import styles from '@/styles/Onboarding.module.css';
import Image from 'next/image';

export default function Onboarding2() {

    const headerTitle = 'Welcome, {user}!';
    const pageLayout = 'layout1';
    const backButton = true;
    const searchBar = true;
    const settings = true;
  
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <div className={styles.iphoneFrame}>
            <main className={`${styles.main}`}>
            <div className={styles.container}>
                <div className={styles.topText}>
                    <h1>Welcome!</h1>
                    <h3>Let's get started,</h3>
                </div>
                <div className={styles.cardBackground}>
                    <div className={styles.image}>
                        <Image src="/images/OnboardingImages/onboarding2.svg" alt="Onboarding1" width={324} height={296} />
                    </div>
                    <div className={styles.bodyText}>
                        <p>Within Neighbourly you can help others with tasks, or do the tasks to help others. Making some extra money and helping your community at the same time!</p>
                    </div>
                    <div>
                        <button className={styles.button}>Continue</button>
                    </div>
                </div>
                </div>
            </main>
          </div>
        </>
    )
}