import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Onboarding.module.css';
import Head from 'next/head';
import { motion } from 'framer-motion';

export default function Onboarding3() {
  const [isExiting, setIsExiting] = useState(false);

  const handleClick = () => {
    setIsExiting(true);
    setTimeout(() => {
      window.location.href = '/';
    }, 2000); 
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.iphoneFrame}>
        <main className={`${styles.main}`}>
          <div className={styles.container}>
            <div className={`${styles.topText} ${isExiting ? styles.fadeOut : ''}`}>
              <h1>Welcome!</h1>
              <h3>Let's get started,</h3>
            </div>
            <div className={styles.cardContainer}>
            <motion.div 
                  className={`${styles.cardBackground}`}
                  initial={{ opacity: 0, x: 420 }}
                  animate={isExiting ? { opacity: 0, x: -420 } : { opacity: 1, x: 0 }}
                  transition={{ duration: 1, ease: "easeIn" }}
                  >        
                <div className={styles.image}>
                  <Image src="/images/OnboardingImages/onboarding3.svg" alt="Onboarding1" width={324} height={296} />
                </div>
                <motion.div 
                className={`${styles.bodyText}`}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5, delay: 0.5 }}
                >       
                  <p>Additionally, you can attend classes held <br></br>by our mentors or partners, and learn a <br></br>variety of new skills.</p>
                  </motion.div>
                  <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5, delay: 1 }}
              >     
                  <button className={styles.button} onClick={handleClick}>Continue</button>
                </motion.div>
                </motion.div>
              </div>
              
            </div>
            
          
        </main>
      </div>
    </>
  );
}