import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import NavBar from '@/components/NavBar';
import TabBar from '@/components/TabBar';


export default function Profile() {

  const headerTitle = 'Username';
  const pageLayout = 'layout1';
  const backButton = true;
  const searchBar = true;
  const settings = true;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar layout={pageLayout} title={headerTitle} backButton={false} searchBar={searchBar} settings={false}/>
        <div className={styles.iphoneFrame}>
          <main className={`${styles.main}`}>
           
          </main>
        <TabBar/>
      </div>
    </>
  )
} 
