import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import NavBar from '@/components/NavBar';
import TabBar from '@/components/TabBar';
import Survey from '@/components/Survey/Survey';

export default function Home() {


  const headerTitle = 'Quiz';
  const pageLayout = 'layout1';
  const backButton = true;

  return (
    <>
      <Head>
        <title>Genie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar layout={pageLayout} title={headerTitle} backButton={backButton} />
      <main className={`${styles.main}`}>
        <div className={styles.appContent}>
          <Survey /> 
        </div>
      </main>
      <TabBar/>
    </>
  )
} 
