import Head from 'next/head';
import styles from '@/styles/Quiz.module.css';
import NavBar from '@/components/NavBar';
import TabBar from '@/components/TabBar';
import Survey from '@/components/Survey/Survey';
import { useState } from 'react';
import Image from 'next/image'

export default function Quiz() {

  const headerTitle = 'Genie';
  const pageLayout = 'layout1';
  const backButton = true;
  const searchBar = true;
  const settings = true;

  // State to manage the visibility of the Survey component and intro text
  const [showSurvey, setShowSurvey] = useState(false);

  // Function to toggle the visibility of the Survey component
  const toggleSurvey = () => {
    setShowSurvey(!showSurvey);
  };

  return (
    <>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.iphoneFrame}>
        <NavBar layout={pageLayout} title={headerTitle} backButton={backButton} />
        <main className={`${styles.main}`}>
          
          {!showSurvey && (
            <div className={styles.quizIntro}>
              <div className={styles.quizIntroTitle}>
              <h1>Let the Neighbourly Genie inspire your next great adventure!</h1>
              </div>
              <div className={styles.quizIntroInner}>
              <div className={styles.quizIntoImage}>
              <Image
                src='/images/quiz/genie.svg'
                alt='image of genie'
                width={300}
                height={300}
              />
              </div>
              <div className={styles.quizIntroDescription}>
              <p>
                The Neighbourly Genie will ask you questions to understand your preferences, 
                then recommends the perfect activity for you based on your answers.
              </p>
              </div>
              <div className={styles.quizIntroButton}>
              <button onClick={toggleSurvey}>Start Quiz</button>
              </div>
              </div>
            </div>
            
          )}
          {showSurvey && <Survey />}
        </main>
        <TabBar/>
      </div>
    </>
  )
}
