import Head from 'next/head';
import styles from '@/styles/Signup.module.css';
import Image from 'next/image';
import Link from 'next/link';

export default function Signup1() {

    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
          <div className={styles.iphoneFrame}>
            <main className={`${styles.main}`}>
              <div className={styles.container}>
              <div className={styles.header}>
                    <h1>Hey there,</h1>
                    <h3>Please fill out the remaining fields.</h3>
                </div>
                <div className={styles.cardBackground}>
                  <div className={styles.progressBar}>
                    <Image src="/images/OnboardingImages/progressBar1.svg" alt="progressBar-1" width={352} height={31} />
                  </div>
                  <div className={styles.container}>
                    <h3 className={styles.title}>Account Info:</h3>
                    <p className={styles.fieldTitle}>Name</p>
                    <input type="text" className={styles.input} placeholder="Please enter your name:" />
                    <p className={styles.fieldTitle}>Email</p>
                    <input 
                      type="text" 
                      className={styles.input} 
                      placeholder="Please enter your email:" 
                      pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"
                      title="Please enter a valid email address."
                    />
                    <p className={styles.fieldTitle}>Phone Number</p>
                    <input type="tel" className={styles.input} placeholder="(+1) Enter your phone number:" />
                    <p className={styles.fieldTitle}>Home Address</p>
                    <input type="text" className={styles.input} placeholder="Please enter your address:" />
                    <Link href="/Signup-2">
                    <input type="submit" className={styles.button} value="Continue" />
                    </Link>
                  </div>
                </div>
              </div>
            </main>
          </div>
        </>
    )
}
