import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import InfoPage from '@/components/InfoPage';
import NavBar from '@/components/NavBar';
import TabBar from '@/components/TabBar';
import Image from 'next/image'
import MentorForm from '@/components/MentorForm';


export default function Home() {

  const headerTitle = 'Mentee Application';
  const pageLayout = 'layout1';
  const backButton = true;
  const searchBar = true;
  const settings = true;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.iphoneFrame}>
        <NavBar layout={pageLayout} title={headerTitle} backButton={backButton} />
        <main className={`${styles.main}`}>
            <MentorForm
                />
        </main>
        <TabBar/>
      </div>
    </>
  )
} 